"""Change price to Float

Revision ID: 758dd543d7d4
Revises: 26b60f4db1dd
Create Date: 2024-10-12 22:58:54.194206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758dd543d7d4'
down_revision = '26b60f4db1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
